# NumPy 切片和索引

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [2]:
import numpy as np

a=np.arange(10)
s=slice(2,7,2)  # 从索引 2 开始到索引 7 停止，间隔为2
print(s)
print(a[s])

slice(2, 7, 2)
[2 4 6]


以上实例中，我们首先通过 arange() 函数创建 ndarray 对象。 然后，分别设置起始，终止和步长的参数为 2，7 和 2。

我们也可以通过冒号分隔切片参数 start:stop:step 来进行切片操作：

In [5]:
a=np.arange(10)
b=a[2:7:2]
print(b)

[2 4 6]


冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [6]:
a=np.arange(10)
b=a[5]
b

5

In [7]:
a=np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [9]:
a=np.arange(10)
print(a[2:5])

[2 3 4]


多维数组同样适用上述索引提取方法：

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

# 从某个索引开始切割
print("从数组索引a[1:]处开始切割")
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
从数组索引a[1:]处开始切割
[[4 5 6]
 [7 8 9]]


切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。

In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[...,1])  # 第2列元素
print(a[1,...]) # 第2行元素
print(a[...,1:]) # 第2列及剩下的所有元素

[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


在多维数组的切片中，使用 , 区分维数。

实例如下：

In [14]:
a=np.arange(0,12)
a.shape=(3,4)
print(a)
注意：冒号分隔切片不包含停止索引
print(a[0:2,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]


在多维数组中，非连续索引切片：

In [15]:
a=np.arange(0,6)
b=np.arange(0,25)
b.shape=(5,5)

#切片向量既可以为array，也可以为list向量
r=np.array([0,1,4])
c=[1,2,4]

print("a:\n",a)
print("a_slice:\n",a[r])

print("b:\n",b)
print("b_slice:\n",b[r,:][:,c])

a:
 [0 1 2 3 4 5]
a_slice:
 [0 1 4]
b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
b_slice:
 [[ 1  2  4]
 [ 6  7  9]
 [21 22 24]]


a[1:3, 2:5] 中逗号左边的为行，右边为列（第 2 行到第 3 行，第 3 列到第 5 列）,输出结果：

In [16]:
a=np.arange(0,80)
a.shape=(8,10)
print(a)
print(a[1:3,2:5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
[[12 13 14]
 [22 23 24]]


索引取的是 n 维数组中对应下标的对象，一个下标的索引，表示取最底层维度第几个元素（ndarray 逻辑结构：数组的数组），类似得到更高维的索引方法，所以索引是会改变维度的的。

切片是取原来 ndarray 的所有维度某个部分相交的的那些元素构成新的 ndarray，切片不会改变维度

In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1],"\n",a[1,1],a[1][1])
print(a[1].ndim,a[1,1].ndim)
print(a[1:],"\n",a[1:2,2:3])
print(a[1:].ndim,a[1:2,2:3].ndim)

[4 5 6] 
 5 5
1 0
[[4 5 6]
 [7 8 9]] 
 [[6]]
2 2


可以用 : 代替 ...：

In [21]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[...,1])  # 第2列元素
print(a[:,1])  # 第2列元素

[2 4 5]
[2 4 5]
