# NumPy 副本和视图

副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。

视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

视图一般发生在：

1、numpy 的切片操作返回原数据的视图。
2、调用 ndarray 的 view() 函数产生一个视图。
副本一般发生在：

Python 序列的切片操作，调用deepCopy()函数。
调用 ndarray 的 copy() 函数产生一个副本。


基本上是正确的。下面是一些补充信息：

在 NumPy 中，如果通过切片或者布尔索引访问 ndarray 的子集，则返回的是原始数据的视图。这意味着，任何对该视图的修改都会反映在原始数据中。但是，如果通过整数索引访问 ndarray 的子集，则返回的是原始数据的副本，因此对该副本的修改不会影响到原始数据。

ndarray 的 view() 方法可以创建一个视图，该视图与原始数组共享数据存储区域，但是具有自己的形状和数据类型。例如，可以使用 reshape() 方法创建一个视图，该视图与原始数组共享数据存储区域，但是具有不同的形状。类似地，可以使用 astype() 方法创建一个视图，该视图与原始数组共享数据存储区域，但是具有不同的数据类型。需要注意的是，修改视图的形状或数据类型可能会影响到原始数组的数据类型，因此需要谨慎使用。


无复制


简单的赋值不会创建数组对象的副本。 相反，它使用原始数组的相同id()来访问它。 id()返回 Python 对象的通用标识符，类似于 C 中的指针。

此外，一个数组的任何变化都反映在另一个数组上。 例如，一个数组的形状改变也会改变另一个数组的形状。

In [3]:
import numpy as np 
a = np.arange(6)  
print ('我们的数组是：')
print (a)
print ('调用 id() 函数：')
print (id(a))
print ('a 赋值给 b：')
b = a 
print (b)
print ('b 拥有相同 id()：')
print (id(b))
print ('修改 b 的形状：')
b.shape =  3,2  
print (b)
print ('a 的形状也修改了：')
print (a)

我们的数组是：
[0 1 2 3 4 5]
调用 id() 函数：
2426723517040
a 赋值给 b：
[0 1 2 3 4 5]
b 拥有相同 id()：
2426723517040
修改 b 的形状：
[[0 1]
 [2 3]
 [4 5]]
a 的形状也修改了：
[[0 1]
 [2 3]
 [4 5]]


视图或浅拷贝


ndarray.view() 方会创建一个新的数组对象，该方法创建的新数组的维数变化不会改变原始数据的维数。

简单来说，共享数据存储区域只是意味着两个对象引用了同一块内存，但是它们的形状和步长不同，因此它们对共享内存的访问方式也不同。通过修改view视图的属性（如形状），并不会影响原始数组的属性。除非它们共享的内存区域中的数据被修改了。

In [7]:
# 最开始 a 是个 3X2 的数组
a = np.arange(6).reshape(3,2)  
print ('数组 a：')
print (a)
print ('创建 a 的视图：')
b = a.view()  
print (b)
print ('两个数组的 id() 不同：')
print ('a 的 id()：')
print (id(a))
print ('b 的 id()：' )
print (id(b))
# 修改 b 的形状，并不会修改 a
b.shape =  2,3
print ('b 的形状：')
print (b)
print ('a 的形状：')
print (a)

b[0,0]=89
print(b)
print(a)

数组 a：
[[0 1]
 [2 3]
 [4 5]]
创建 a 的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的 id() 不同：
a 的 id()：
2426766314160
b 的 id()：
2426766314352
b 的形状：
[[0 1 2]
 [3 4 5]]
a 的形状：
[[0 1]
 [2 3]
 [4 5]]
[[89  1  2]
 [ 3  4  5]]
[[89  1]
 [ 2  3]
 [ 4  5]]


使用切片创建视图修改数据会影响到原始数组：

In [5]:
arr = np.arange(12)
print ('我们的数组：')
print (arr)
print ('创建切片：')
a=arr[3:]
b=arr[3:]
a[1]=123
b[2]=234
print(arr)
print(id(a),id(b),id(arr[3:]))

我们的数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
创建切片：
[  0   1   2   3 123 234   6   7   8   9  10  11]
2426722746800 2426744409616 2426744409904


变量 a,b 都是 arr 的一部分视图，对视图的修改会直接反映到原数据中。但是我们观察 a,b 的 id，他们是不同的，也就是说，视图虽然指向原数据，但是他们和赋值引用还是有区别的。

副本或深拷贝
ndarray.copy() 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。

In [8]:
a = np.array([[10,10],  [2,3],  [4,5]])  
print ('数组 a：')
print (a)
print ('创建 a 的深层副本：')
b = a.copy()  
print ('数组 b：')
print (b)
# b 与 a 不共享任何内容  
print ('我们能够写入 b 来写入 a 吗？')
print (b is a)
print ('修改 b 的内容：')
b[0,0]  =  100  
print ('修改后的数组 b：')
print (b)
print ('a 保持不变：')
print (a)

数组 a：
[[10 10]
 [ 2  3]
 [ 4  5]]
创建 a 的深层副本：
数组 b：
[[10 10]
 [ 2  3]
 [ 4  5]]
我们能够写入 b 来写入 a 吗？
False
修改 b 的内容：
修改后的数组 b：
[[100  10]
 [  2   3]
 [  4   5]]
a 保持不变：
[[10 10]
 [ 2  3]
 [ 4  5]]


In [9]:
a = np.arange(4)
b = a
# 改变a中第一个元素的值
a[0] = 9
print(a)
print(b)

[9 1 2 3]
[9 1 2 3]


可以看到，改变 a 后，b 的值也跟着变了，这是为什么呢？

实际上，变量 a 中并没有存储任何的值，它只是指向了一个内存地址，而这个地址里存储着 array 具体的内容，当把a赋值给b的时候，实际上是把 a 指向内存中某对象的链接赋给了 b，也就是说，现在 a 和 b 都指向了同一个对象。

因此，在改变了内存中 array 的值后，而 a 与 b 都引用了该 array 对象，所以都一起发生了变化。

这种只是将内存引用赋值给另一个变量的操作叫做浅拷贝。

那什么是深拷贝呢，深拷贝则会重新分配内存空间，生成新的变量名和内存区域，所以不会受到原始数据的影响。

In [10]:
# 浅拷贝只是拷贝数据的地址
# 对于数组的数据结构：array 对应一块儿内存地址，数组里每个对象对应一块儿数据结构
# view方法拷贝了所有元素的内存结构，但array的内存地址不同。
# 以reshape不会影响原数组，但是赋值会影响。

import numpy as np  
a = np.arange(1, 12, 2)    
print(a)    
b = a.view()    
print("id(a) == id(b) ? %d" % id(a) == id(b))    
print("a的id=%d" % id(a))    
print("b的id=%d" % id(b))    
print(id(a[0]) == id(b[0]))    
print("a[0]的id=%d" % id(a[0]))    
print("b[0]的id=%d" % id(b[0]))    
print("reshape数组:", end="")    
b.shape = 2, 3    
print(b)    
print("原数组:", end="")    
print(a)    
print("替换元素:", end="")    
b[0][0] = -1    
print(b)    
print("原数组:", end="")    
print(a)

[ 1  3  5  7  9 11]
False
a的id=2426766313584
b的id=2426766314736
True
a[0]的id=2426767502704
b[0]的id=2426767501680
reshape数组:[[ 1  3  5]
 [ 7  9 11]]
原数组:[ 1  3  5  7  9 11]
替换元素:[[-1  3  5]
 [ 7  9 11]]
原数组:[-1  3  5  7  9 11]
