# NumPy 高级索引

NumPy 比一般的 Python 序列提供更多的索引方式。

除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。

NumPy 中的高级索引指的是使用整数数组、布尔数组或者其他序列来访问数组的元素。相比于基本索引，高级索引可以访问到数组中的任意元素，并且可以用来对数组进行复杂的操作和修改。

整数数组索引

整数数组索引是指使用一个数组来访问另一个数组的元素。这个数组中的每个元素都是目标数组中某个维度上的索引值。
以下实例获取数组中 (0,0)，(1,1) 和 (2,0) 位置处的元素。

In [2]:
import numpy as np

x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


以下实例获取了 4X3 数组中的四个角的元素。 行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]。

In [18]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print("我们的数组时是：")
print(x)
print("\n")
rows=np.array([[0,0],[3,3]]) #取行索引号
cols=np.array([[0,2],[0,2]]) #取列索引号
y=x[rows,cols] #生成一个二维数组：取第一行第一列、第一行第3列 和 第4行第一列、第4行第三列的数
print("这个数组的四个角元素是：")
print(y)
rows=np.array([0,0,3,3]) #取行索引号
cols=np.array([0,2,0,2]) #取列索引号
y=x[rows,cols] 
print("这个数组的四个角元素是：")
print(y)

我们的数组时是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]
这个数组的四个角元素是：
[ 0  2  9 11]


In [4]:
y=x[[0,3],:][:,[0,2]] #生成一个二维数组：取第一行第一列、第一行第3列 和 第4行第一列、第4行第三列的数
print(y)
print("---------------------")
y = x[[[0,0],[3,3]],[[0,2],[0,2]]]   #生成一个二维数组：取第一行第一列、第一行第3列 和 第4行第一列、第4行第三列的数
print (y)
print("---------------------")
y = x[[[0],[3]],[[2],[2]]]           #生成一个二维数组：第一行第3列 和 第4行第三列的数
print (y) 
print("---------------------")
y = x[[0,0,3,3],[0,2,0,2]]           #生成一个一维数组：取第一行第一列和第四行第一列的数
print (y)
print("---------------------")
y = x[[3,3],[0,2]]                   #生成一个一维数组：取第4行第一列和第4行第3列的数
print (y)
print("---------------------")
y = x[[0,3],[[0,2],[0,2]]]           #生成一个二维数组：由第一行第一列和第4行第三列的数为一组生成两组
print (y)
print("---------------------")
y = x[[[0,0],[3,3]],[0,2]]           #生成一个二维数组：取第一行第一列、第一行第3列 和 第4行第一列、第4行第三列的数
print (y)

[[ 0  2]
 [ 9 11]]
---------------------
[[ 0  2]
 [ 9 11]]
---------------------
[[ 2]
 [11]]
---------------------
[ 0  2  9 11]
---------------------
[ 9 11]
---------------------
[[ 0 11]
 [ 0 11]]
---------------------
[[ 0  2]
 [ 9 11]]


返回的结果是包含每个角元素的 ndarray 对象。

可以借助切片 : 或 … 与索引数组组合。如下面例子：

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[1:3,1:3]
c=a[1:3,[1,2]]
d=a[...,1:]
print(b)
print(c)
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


布尔索引
我们可以通过一个布尔数组来索引目标数组。

布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

以下实例获取大于 5 的元素：

In [19]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print("我们的数组是：")
print(x)
print("\n")
# 现在我们会打印出大于5的元素
print(x[x>5])
print(x>5)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[ 6  7  8  9 10 11]
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


以下实例使用了 ~（取补运算符）来过滤 NaN。
np.isnan(a) 返回一个布尔数组，其中True表示元素是NaN，False表示元素不是NaN。例如，在这个例子中，它将返回一个数组 [True False False True False False False]。

然后，使用 ~ 操作符对这个布尔数组进行按位取反操作。这将把所有的 True 变成 False，把所有的 False 变成 True。因此，最终结果是 [False True True False True True True]。

这个布尔数组可以用作索引来选择原始数组中的元素。在这个例子中，它选择了所有不是NaN的元素。

In [21]:
a=np.array([np.nan,1,2,np.nan,3,4,5])
print(np.isnan(a))
print(a[~np.isnan(a)])

[ True False False  True False False False]
[1. 2. 3. 4. 5.]


以下实例演示如何从数组中过滤掉非复数元素。

In [22]:
a=np.array([1,2+6j,5,3.5+5j])
print(np.iscomplex(a))
print(a[np.iscomplex(a)])

[False  True False  True]
[2. +6.j 3.5+5.j]


花式索引
花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。

对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素，如果目标是二维数组，那么就是对应下标的行。

花式索引跟切片不一样，它总是将数据复制到新数组中。

一维数组
一维数组只有一个轴 axis = 0，所以一维数组就在 axis = 0 这个轴上取值：

In [26]:
x=np.arange(9)
print(9)
# 一维数组读取指定下标对应的元素
print("-------读取下标对应的元素-------")
x2=x[[0,6]] # 使用花式索引
print(x2)
print(x2[0])
print(x2[1])

9
-------读取下标对应的元素-------
[0 6]
0
6


二维数组
1、传入顺序索引数组

In [10]:
x=np.arange(32).reshape((8,4))
print(x)
# 二维数组读取指定下标对应的行
print("-------读取下标对应的行-------")
print(x[[4,2,1,7]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------读取下标对应的行-------
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


2、传入倒序索引数组

In [11]:
x=np.arange(32).reshape((8,4))
print(x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


3、传入多个索引数组（要使用 np.ix_）

np.ix_ 函数就是输入两个数组，产生笛卡尔积的映射关系。

笛卡尔乘积是指在数学中，两个集合 X 和 Y 的笛卡尔积（Cartesian product），又称直积，表示为 X×Y，第一个对象是X的成员而第二个对象是 Y 的所有可能有序对的其中一个成员。

例如 A={a,b}, B={0,1,2}，则：
A×B={(a, 0), (a, 1), (a, 2), (b, 0), (b, 1), (b, 2)}
B×A={(0, a), (0, b), (1, a), (1, b), (2, a), (2, b)}

In [12]:
x=np.arange(32).reshape((8,4))
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


关于 np.ix_ 的具体使用：

正文中没有详细说 np.ix_ 是怎么回事，我看了一下 help(numpy.ix_)，说的比较详细。比如正文中举的例子中，x[np.ix_([1,5,7,2],[0,3,1,2])]这句话会输出一个4*4的矩阵，其中的元素分别是：
x[1,0] x[1,3] x[1,1] x[1,2]
x[5,0] x[5,3] x[5,1] x[5,2]
x[7,0] x[7,3] x[7,1] x[7,2]
x[2,0] x[2,3] x[2,1] x[2,2]

相当于：

In [13]:
y=np.array([[x[1,0], x[1,3], x[1,1], x[1,2]],\
            [x[5,0], x[5,3], x[5,1],x[5,2]],\
            [x[7,0] ,x[7,3], x[7,1], x[7,2]],\
            [x[2,0], x[2,3], x[2,1], x[2,2]]])

关于多条件的布尔索引

使用 & 连接两个条件，输出大于 5 且小于 10 的元素 print(x[x>5 & x<10])：
在 numpy 中会报错：The truth value of an array with more than one element is ambiguous
三个实用的解决方法：

1、条件加小括号
2、使用 np.logical_and 方法
3、使用 np.all 方法

In [14]:
x=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('原数组：\n', x)
print('大于5且小于10的元素：')
print('条件加小括号：')
print(x[(x>5) & (x<10)])
print('使用np.logical_and方法：')
print(x[np.logical_and(x>5,x<10)])
print('使用np.all方法：')
print(x[np.all([x>5,x<10],axis=0)])

原数组：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
大于5且小于10的元素：
条件加小括号：
[6 7 8 9]
使用np.logical_and方法：
[6 7 8 9]
使用np.all方法：
[6 7 8 9]


另外，布尔索引不一定针对数组的所有元素，可以针对某一列的数据，进而提取需要的数组。

In [15]:
a=np.array([
    [1,1,0],
    [2,1,0],
    [3,2,0],
    [4,2,0],
    [5,3,0]])
b=a[(a[...,0]>2) & (a[...,1]<3),...]
print(b)

[[3 2 0]
 [4 2 0]]


这种索引的行列对应的关系像数组相乘的对应关系:

In [16]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print("我们的数组是：\n",x)

我们的数组是：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
rows=np.array([[0,0],[3,3]])
cols=np.array