# 用slice()函数创建切片对象

In [2]:
# 创建一个一维数组
import numpy as np
a=np.arange(20)
s=slice(2,7,2)
print(s)
print(a[s])

slice(2, 7, 2)
[2 4 6]


[start:stop:step] 直接传入切片参数

In [6]:
a=np.arange(20)
c0=a[2]
c1=a[2:7:1]
c2=a[10:]
c3=a[:10]
c4=a[::-1]
c5=a[:8:-1]
print(c0,'\n',c1,'\n',c2,'\n',c3,'\n',c4,'\n',c5)

2 
 [2 3 4 5 6] 
 [10 11 12 13 14 15 16 17 18 19] 
 [0 1 2 3 4 5 6 7 8 9] 
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0] 
 [19 18 17 16 15 14 13 12 11 10  9]


多维数组使用切片

In [7]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print('a[1]:\n',a[1])
print('a[1:]:\n',a[1:])
print('a[::2]:\n',a[::2])
print('a[::-1]:\n',a[::-1])

a[1]:
 [3 4 5]
a[1:]:
 [[3 4 5]
 [4 5 6]]
a[::2]:
 [[1 2 3]
 [4 5 6]]
a[::-1]:
 [[4 5 6]
 [3 4 5]
 [1 2 3]]


切片对象中包含 “…”
切片对象 [] 中包含省略号…
作用： 使得 选择元组的长度 = 数组的维度

如果在行位置使用 … return包含行中元素的ndarray

In [9]:
import numpy as np
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print('第2列元素',a[::,1])
# 等价于
print('第2列元素',a[...,1])

print('第2行元素',a[1,])
#d等价于
print('第2行元素',a[1,::])
#d等价于
print('第2行元素',a[1,...])
print('第2列开始剩下的所有列\n',a[::,1:])
#等价于
print('第2列开始剩下的所有列\n',a[...,1:])


第2列元素 [2 4 5]
第2列元素 [2 4 5]
第2行元素 [3 4 5]
第2行元素 [3 4 5]
第2行元素 [3 4 5]
第2列开始剩下的所有列
 [[2 3]
 [4 5]
 [5 6]]
第2列开始剩下的所有列
 [[2 3]
 [4 5]
 [5 6]]


总结：
[]中，逗号，区分的是维度，冒号：区分的是索引，省略号… 用来代替全索引长度